config/routes.rb
Rails.application.routes.draw do
  get 'create_photo', to: 'photo#new'
  root 'photo#index'
  post 'create_photo', to: 'photo#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  include ImageUploader::Attachment(:image) 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photo_controller.rb
class PhotoController < ApplicationController
  def create
    @ph = Photo.create(photo_params)
    @ph.save!
  end
  
  def new
    @photo = Photo.new
  end
  
  def index
    @photos = Photo.all
  end

  private

  def photo_params
    params.require(:photo).permit(:image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Attach</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photo/index.html.erb
<% if @photos.any? %>
  <% @photos.each do |photo| %>
   <%= image_tag photo.image_url, class: "img" %> 
  <% end %>
<% end %>

app/views/photo/new.html.erb
<%= form_for @photo, url: create_photo_url do |f| %>
  <%= f.hidden_field :image, value: @photo.cached_image_data %>
  <%= f.file_field :image %>
  <%= f.submit %>
<% end %>